### ISSUE TITLE
Single Select Clear: Optional select fields should display clear button

### ISSUE THREAD

**Issue by ogunb** [Trendyol/grace#608]
### Describe the problem or use case

User should be able to opt out on their choice if the select box is not required.

### Proposed solution

Given required prop is not provided, display clear button.

### Alternatives considered

This could also be implemented as an attribute.

### Additional technical context

We already have the clear button, this shouldn't be a hassle.

**Comment by muratcorlu** [comment]
Looks like a nice suggestion. @buseselvi what do you think to show "clear selection button" to select, even if it's in single selection mode?

**Comment by buseselvi** [comment]
I think it is necessary to add the Clear button to the single select as well. But we need to keep it optional because, for the places like pagination, we bring the select selected and it should never be empty.

**Comment by muratcorlu** [comment]
What about defining a rule like "If it's **not** required, then the clear button should be visible when a selection is done"? If we set a select required with a default selection, then there will be no clear button and it will be not possible to make it invalid (like in pagination).

But I'm not sure about running the same rule on multi-selection mode. 🤔

**Comment by buseselvi** [comment]
I looked at the benchmarks, and the clear button is always visible in multi-select, but it is optional in single-select.

**Comment by ogunb** [comment]
We'll update the if as multiple or not required then.

I'll send a PR for this later today.
