### ISSUE TITLE
Implementation of testing mechanism

### ISSUE THREAD

**Issue by leventozen** [Trendyol/grace#71]
- [x] Every component should have fully covered (100% code coverage) unit tests. So, implement coverage check.
- [x] Coverage report should be generated.
- [x] Coverage threshold should be checked in commits and also in GitHub Actions.
- [x] _Automated visual tests should be implemented for all components. A screenshot comparison would be done in every commit in PRs_  -> **will be evaluated in another issue**
- [x] Testing rules and best practices should be documented

**Comment by muratcorlu** [comment]
Closing issue as related PR is merged.
